name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build the site
        run: npm run build

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 2222 -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Rsync & atomic swap
        run: |
          rsync -az --delete-after dist/ \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/incoming/$GITHUB_SHA
          ssh -p 2222 \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
            "bash /usr/local/bin/swap_symlink.sh $GITHUB_SHA"